backend/admin_honeypot/urls.py
from admin_honeypot import views
from django.urls import path, re_path

app_name = 'admin_honeypot'

urlpatterns = [
    path('login/', views.AdminHoneypot.as_view(), name='login'),
    re_path(r'^.*$', views.AdminHoneypot.as_view(), name='index'),
]

backend/index/urls.py
from django.urls import path

from index import views

urlpatterns = [
    path('send/', views.EmailView.as_view(), name='send_email'),
]

backend/server/urls.py
from django.urls import path, include, re_path, reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls import url

from server.admin import admin_site
from sduser.utils import verify_email
from sduser.forms import SDPasswordChangeForm, SDPasswordResetForm
from index.views import angularLogIn

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

import datetime

urlpatterns = [
    path('email/', include('index.urls')),
    path('admin/password_change/',
         auth_views.PasswordChangeView.as_view(
             form_class=SDPasswordChangeForm,
             success_url=reverse_lazy('admin:password_change_done')
         ), name='password_change'),
    path('admin/password_reset/',
         auth_views.PasswordResetView.as_view(
             form_class=SDPasswordResetForm,
         ),
         name='admin_password_reset',),
    path('admin/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done',),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm',),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete',),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('fd-admin/', admin_site.urls),
    path('auth/', include('sduser.urls_auth')),
    path('user/', include('sduser.urls')),
    path('user/', include('restaurant.urls_user')),
    path('subscriber/', include('subscriber_profile.urls')),
    path('owner/', include('restaurant_owner.urls')),
    path('article/', include('article.urls')),
    path('dish/', include('restaurant.urls_dish')),
    path('restaurant/', include('restaurant.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('newsletter/', include('newsletter.urls')),
]

schema_view = get_schema_view(
    openapi.Info(
        title="Find Dining APIs",
        default_version='v2',
        description="Documentation of all APIs used for the Find Dining project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="info@finddining.ca"),
        license=openapi.License(
            name=str(datetime.datetime.now().year)+" Find Dining"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

if settings.DEBUG:
    doc_urls = [
        url(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
        url(r'^swagger/$', schema_view.with_ui('swagger',
                                               cache_timeout=0), name='schema-swagger-ui'),
        url(r'^redoc/$', schema_view.with_ui('redoc',
                                             cache_timeout=0), name='schema-redoc'),
    ]
    urlpatterns.extend(doc_urls)

urlpatterns = [
    path('verification/<uidb64>/<token>/', verify_email, name='verify_email'),
    path('login/', angularLogIn, name="login"),
    # prefix all URLpatterns with api/ i.e. api/urlpattern
    path('api/', include(urlpatterns))]

'''
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
'''

backend/templates/verify_email/activation_notify.html
<p>Hello {{ user.username }},</p>
<p>Your account for Find Dining has been activated by a system administrator.</p>
<p>No action is required. You may now <a href="{{ protocal }}://{{ domain }}{% url 'login' %}">log in</a> to the site using the account registered with this email.</p>

<p>Thanks,</p>
<p>Your Find Dining team</p>
{% autoescape off %}
{% endautoescape %}

backend/templates/verify_email/deactivation.html
<p>Hello {{ user.username }},</p>
<p>Your account for Find Dining has been deactivated.</p>
<p>If this was not requested by you, please follow the link below to reactivate. We suggest you change your password immediately.</p>
<p><a href="{{ protocal }}://{{ domain }}{% url 'verify_email' uidb64=uid token=token %}" class="verification" >Reactivate my account for Find Dining</a></p>

<p>Thanks,</p>
<p>Your Find Dining team</p>
{% autoescape off %}
{% endautoescape %}

backend/templates/verify_email/deactivation_notify.html
<p>Hello {{ user.username }},</p>
<p>Your account for Find Dining has been deactivated by a system administrator.</p>
<p>If you think this is a mistake, please reply to this email with an explanation.</p>

<p>Thanks,</p>
<p>Your Find Dining team</p>
{% autoescape off %}
{% endautoescape %}

backend/templates/verify_email/failure.html
{% extends "verify_email/verify_base.html" %}
{% load static %}

{%block content%}


<div class="container">
    <div class="row" style="margin: 100px 0px; text-align: center; font-family: Arial, Helvetica, sans-serif;">
        <div class="col">
            <img src="{% static 'images/x_mark.png' %}" alt="checkmark" style="width: 150px; height: auto; margin-bottom: 50px;" />
            <div class="container" style="padding-bottom: 10px;">
                <h1 style="font-size: calc(25px + 4vw);">
                    {{status}}
                </h1>
            </div>
            <hr style="background-color: black; width: 150px;">

            <div class="container">
                <h1 style="font-size: calc(15px + 1.5vw);">
                    {{msg}}
                </h1>
            </div>

            <div class="mt-5">
                <h1 style="font-size: calc(15px + .5vw);">
                    The token / link is already used or modified. Can not validate faulty link...
                </h1>
            </div>
        </div>
    </div>
</div>

{%endblock%}

backend/templates/verify_email/promotion_notify.html
<p>Hello {{ user.username }},</p>
<p>Your account for Find Dining has been promoted to have administrative access by a system administrator.</p>
<p>No action is required. You may now <a href="{{ protocal }}://{{ domain }}{% url 'admin:index' %}">log in</a> to the administrative panel using the account registered with this email.</p>

<p>Thanks,</p>
<p>Your Find Dining team</p>
{% autoescape off %}
{% endautoescape %}

backend/templates/verify_email/success.html
{% extends "verify_email/verify_base.html" %}
{% load static %}

{%block content%}


<div class="container">
    <div class="row" style="margin: 100px 0px; text-align: center; font-family: Arial, Helvetica, sans-serif;">
        <div class="col">
            <img src="{% static 'images/check_mark.png' %}" alt="checkmark" style="width: 150px; height: auto; margin-bottom: 50px;" />
            <div class="container" style="padding-bottom: 10px;">
                <h1 style="font-size: calc(25px + 4vw);">
                    {{status}}
                </h1>
            </div>
            <hr style="background-color: black; width: 150px;">

            <div class="container">
                <h1 style="font-size: calc(15px + 1.5vw); color: rgba(119,119,119,255);">
                {{msg}}
                </h1>
            </div>

        </div>
    </div>
    <div class="row justify-content-center">
        <a href="{{link}}" class="btn btn-primary" style="border-radius: 20px; margin-left: 10px; margin-right: 10px;">
            Log In 
        </a>
    </div>

</div>

{%endblock%}

backend/templates/verify_email/verification.html
<p>Hello {{ user.username }},</p>
<p>Follow this link to verify your email address.</p>
<p><a href="{{ protocal }}://{{ domain }}{% url 'verify_email' uidb64=uid token=token %}" class="verification" >Verify My Email Address with Find Dining</a></p>
<p>If you didn't ask to verify this address, you can ignore this email.</p>
<p>Thanks,</p>
<p>Your Find Dining team</p>
{% autoescape off %}
{% endautoescape %}

backend/templates/verify_email/verify_base.html
{%load static%}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,wght@700,&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC:wght@700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
    
    <!-- CSS for navbar and footer -->
    <link rel="stylesheet" type="text/css" href="{% static "css/navbar.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/footer.css" %}">

    <!-- Find Dining Icon -->
    <link rel="icon" type="image/x-icon" href="{% static "images/favicon.ico" %}">

    <title>{{status}}</title>
  </head>
  <body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg" role="navigation">
      <a href="/">
        <img src="{% static 'images/find_dining_logo.png' %}" class="logo" alt="Find Dining logo, click to go to home page" />
      </a>
      
      <a class="word" href="/">
        <span class="find">FIND </span>
        <span class="dining">DINING </span> <br />
        <span class="scarborough">SCARBOROUGH</span>
      </a>

      <div class="navbar-nav ml-auto" >
        <div class="nav-item" tabindex="0">
          <a class="nav-link" href="/" >
            Home
          </a>
        </div>
        <p class="nav-item separator">|</p>
        <div data-toggle="collapse" data-target=".navbar-collapse.show" class="nav-item">
          <a href="https://www.facebook.com/finddiningscarborough/" target="_blank"  tabindex="0">
            <img src="{% static 'images/facebook_icon.png' %}" class="icon" alt="Facebook"  />
          </a>
          <a href="https://twitter.com/FDscarborough" target="_blank" tabindex="0">
            <img src="{% static 'images/twitter_icon.png' %}" class="icon" alt="Twitter" />
          </a>
          <a href="https://www.instagram.com/finddiningscarborough/" target="_blank"  tabindex="0">
            <img src="{% static 'images/instagram_icon.png' %}" class="icon" alt="Instagram"  />
          </a>
        </div>
      </div>
    </nav>
    {% endblock %}

    {% if messages%}
      {% for message in messages %}
        <div class="alert alert-{{message.tags}}">
          {{message}}
      {% endfor %}
        </div>
    {% endif %}


    {%block content%}{%endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
  <footer role="contentinfo">
    <div class="footer-content" class="col">
      <div id="footer-main-links" class="row">
        <div class="col">
          <img
            src="{% static 'images/scarborough_dining_dark.png' %}"
            class="footer-logo"
            alt="Find Dining Scarborough footer logo"
          />
          <p class="copy-right">&copy; 2021 Find Dining</p>
        </div>
        <div class="col-4">
          <p class="footer-title"><b>Navigate</b></p> <br>
          <div class="row" style="padding: 0px 5px">
            <div class="col">
              <a class="footer-links" href="/about-us">About Us</a><br>
              <a class="footer-links" href="/get-involved">Get Involved</a>
            </div>
            <div class="col">
              <a class="footer-links" href="/terms-of-service">Terms of Service</a><br>
              <a class="footer-links" href="/privacy-policy">Privacy Policy</a>
            </div>
          </div>
        </div>
        <div class="col-2">
          <p class="footer-title-2"><b>Find Us</b></p> <br>
          <div class="row" style="padding-left: 6px;">
            <a href="https://www.facebook.com/finddiningscarborough/" target="_blank"  tabindex="0">
              <img src="{% static 'images/facebook_icon.png' %}" class="icon" alt="Facebook" ngbTooltip="View Find Dining Facebook Page" />
            </a>
            <a href="https://twitter.com/FDscarborough" target="_blank" tabindex="0">
              <img src="{% static 'images/twitter_icon.png' %}" class="icon" alt="Twitter" ngbTooltip="View Find Dining Twitter Page" />
            </a>
            <a href="https://www.instagram.com/finddiningscarborough/" target="_blank"  tabindex="0">
              <img src="{% static 'images/instagram_icon.png' %}" class="icon" alt="Instagram" ngbTooltip="View Find Dining Instagram Page" />
            </a>
          </div>
        </div>
      </div>

      <hr>

      <div class="row">
        <div class="col-8">
          <p class="partners" tabindex="0">
            Find Dining is a program to promote independent restaurants in Scarborough and is supported by the City of
            Toronto, in partnership with the University of Toronto Scarborough and Centennial College
          </p>
        </div>
        <div class="row col-4">
          <a href="https://www.toronto.ca/" target="_blank">
            <img src="{% static 'images/sponsor_toronto.png' %}" class="sponsor" alt="Sponsor: City of Toronto" />
          </a>
          <a href="https://www.utsc.utoronto.ca/home/" target="_blank">
            <img src="{% static 'images/sponsor_uoft.png' %}" class="sponsor" alt="Sponsor: University of Toronto Scarborough" />
          </a>
          <a href="https://www.centennialcollege.ca/" target="_blank">
            <img src="{% static 'images/sponsor_centennial.png' %}" class="sponsor"  alt="Centennial College" />
          </a>
        </div>
      </div>
    </div>
  </footer>
</html>